### ISSUE TITLE
No documentation for microservices.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#109]
Typically microservices are part of the toolkit and documented with the SPLDOC of the toolkit.

However the two microservices in this project are outside the toolkit and no documentation for them seems to be available.

See: https://github.com/IBMStreams/streamsx.microservice/blob/develop/IMPLEMENTATION_GUIDELINES.md

**Comment by ddebrunner** [comment]
I would recommend moving them to the toolkit and using the recommended namespace style.

**Comment by markheger** [comment]
What would be the advantage of having the microservice projects in the toolkit?
How shall they be built?
Why should the toolkit depend on other toolkits like JSON, just because of microservices?
User should use the released sab files of the microservices.

**Comment by ddebrunner** [comment]
Advantages are it's a simple standard approach, the toolkit provides operators, functions, types and microservices. I don't need to download/use N+1 toolkits to use N microservices, a single toolkit is sufficient. At least a single toolkit per microservice seems excessive, when all the microservices are probably related, and are typically related to their "parent" toolkit through types. 

Like any other application, not sure about what the _how shall they be built_ is getting at?

No real issue depending on JSON and topology toolkits, both are shipped as part of the product.

I can't use the sab files because there's no documentation or indication what os/platform they were built for. Also, currently I can't easily script running the sab files against the cloud service, so instead I would use `streamsx-runner` pointing at their main composites.

**Comment by markheger** [comment]
## Proposed actions

1. Move microservice main composite files into toolkit
   - move
`streamsx.monitoring/microservices/MetricsIngestService/com.ibm.streamsx.monitoring.service/MetricsIngestService.spl`
and 
`streamsx.monitoring/microservices/MetricsMonitorService/com.ibm.streamsx.monitoring.service/MetricsMonitorService.spl`
to 
`streamsx.monitoring/com.ibm.streamsx.monitoring/com.ibm.streamsx.monitoring.service`

2. Document usage and interfaces of microservices
    - Provide example in documentation, how to launch them with `streamxs-runner`
3. Adapt existing test case using the microservices to new location
3. Provide sab files with a release with platform/Streams Version info
    - Adapt build scripts to build them from new location

**Comment by ddebrunner** [comment]
Minor change: I would say the target namespace should be: `com.ibm.streamsx.monitoring.metrics.services`

 - these are services specific to metrics, I was adding the job microservicesg to `com.ibm.streamsx.monitoring.job.services`
 - plural of 'service' as per the implementation guidelines for microservices.
