### ISSUE TITLE
Create failed PE detector microservice.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#112]
A microservice that detects if a PE has been stopped for a period of time (e.g. a minute). Publishes a tuple if it detects such a PE. Ideally it would differentiate between PEs that were manually stopped and those that failed and could not restart after 10 attempts.

Would use the job status microservice from #111.

Use cases (in separate microservices):

- Issue alerts (pager, slack etc.) when a PE cannot be restarted.
- Automated attempts to restart PE periodically. This is the original use case I had in mind, once MessageHub went down for a period of time (e.g. an hour), and the Streams application PE did not restart because it had restarted 10 times in a short time when the original failure occurred. I envisage microservices that would periodically try to restart such PEs to ensure the application returns as soon as it can.

I have initial code, needs more work to fully develop to detect manually stopped PEs etc.

**Comment by ddebrunner** [comment]
Also an attempt to use the monitoring toolkit to build "smart" monitoring and recovery solutions for Streams rather than force everything into the core product.

**Comment by markheger** [comment]
Initial version is part of 2.0 release
