### ISSUE TITLE
Overview documentation for what is domain/instance is monitored.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#124]
For `JobSource` and `MetricsSource` there needs to be overview documentation as to how the JMX connection is setup using the operator parameters. At the moment each parameter is described individually and it's hard to figure out what needs to be setup to monitor something that is not the current instance.

- If `domainId` is **not** the domain of the instance running the operators:
   - then`connectionUrl` must be set, don't think this is clearly documented.
   - this mode may only be supported if running standalone which is a big limitation, not sure that's documented.
 - Not providing a filter document is broken (at least not useful with no warning) (see #123 ) if
   - `domainId` is **not** the domain of the instance running the JMX source operators
   - intended instance is not the instance running the JMX source

**Comment by ddebrunner** [comment]
Maybe `sslOption` is another parameter that is impacted by this, since the

**Comment by ddebrunner** [comment]
At least having these common patterns documented with examples would be helpful.
- Monitoring the same domain and instance as where the monitoring code is running.
- Monitoring the same domain but different instance from the monitoring code is running.
- Monitoring the a different domain and different instance from where the monitoring code is running.

**Comment by markheger** [comment]
* [ ] update iopages
