### ISSUE TITLE
scanPeriod can be confusing.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#128]
In `JobStatusSource` parameter `scanPeriod` is the frequency check for updates to the filter document (through an application configuration).

In `MetricsSource` parameter `scanPeriod` is overloaded to be both the frequency check for updates to the filter document and how often metrics are scanned for.

Frequently checking the application configuration is not recommended, but  `MetricsSource` pretty much forces this behaviour.

**Comment by markheger** [comment]
change the behaviour(or new parameter)/documentation in 2.0 release

**Comment by markheger** [comment]
introduced `checkPeriod` parameter(for filter document updates in application configuration)
