### ISSUE TITLE
Support Metric Sink for integration in IBM Bluemix Metric/Log Service

### ISSUE THREAD

**Issue by rnostream** [IBMStreams/streamsx.monitoring#35]
IBM Bluemix provides a solution/service for metric/log storage and appropriate visualization with Grafana (metrics) and Kibana (logs). 
This is ready to use. An application or service just needs to write its metrics/log records via the provided API and one can immediately see the metrics/logs in dashboards created on ones own need.
Any Streams application can immediately show and process own metrics in IBM Bluemix when this new MetricSink would be available.

**Comment by ddebrunner** [comment]
Which service is this, can a link to the service be added (e.g. to its catalog entry).

**Comment by rnostream** [comment]
This is not a service from catalog which Bluemix user can choose. It is a service from the platform itself which other services on Bluemix may use to send their logs and metrics to a central place. Actual some services use this, e.g. MessageHub, CF Apps, Container
It's the 'logmet' service. It stores logs and metrics on an organization-space level. A Bluemix user may login and see/create grafana/kibana dashboards by logging in with space/organization/user/password.
As far as I read the data is stored 7 days with 1 GB /day for logs.
The usual way is using collectd with an output plugin mtlumberjack (provided on Bluemix).

**Comment by ddebrunner** [comment]
This seems to be a visible service now, with the ability to send it metrics.

https://console.bluemix.net/catalog/services/monitoring

**Comment by ddebrunner** [comment]
I created some initial code for sending metrics to the Grafana attached to the IBM Cloud monitoring service, basically two services:

- `SimplifyMetricsService` that takes `Notification` tuples from `MetricsIngestService` and republishes them as a simple schema of `{name, kind, value, ts}`. The name is a multi-dotted name created from the various elements of  `Notification`.
- Then a simple Streams Python app that batches them up and sends them a a SendMetric REST call into the monitoring service.

**Comment by ddebrunner** [comment]
Then I could graph the metrics and create alerts on them.
