### ISSUE TITLE
Filter document format not described.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#41]
I was looking at the SPLDOC to try and use the toolkit and no explanation of the filter document format is provided. There is a section for it:

https://ibmstreams.github.io/streamsx.metrics/doc/spldoc/html/tk$com.ibm.streamsx.metrics/op$com.ibm.streamsx.metrics$MetricsSource$1.html

but it contains little information.

Some examples would be useful as well as a formal definition of what keys are expected, what their values are meant to be.

**Comment by Alex-Cook4** [comment]
The example document in the sample also seems to be invalid JSON when I run it through a validator: https://github.com/IBMStreams/streamsx.monitoring/blob/master/samples/com.ibm.streamsx.monitoring.metrics.test/etc/MetricsSource_MonitorEverything.json Is this expected?

**Comment by markheger** [comment]
@Alex-Cook4 You are right, several commas needs to be removed in the JSON to pass the validator.

**Comment by markheger** [comment]
released with 1.2.0
