### ISSUE TITLE
Composites/microservices that perform high-level monitoring.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#42]
Is this a suitable repo for having microservices that support common monitoring tasks, such as a service that creates an alert tuple each time a job is having issues?

Then these alerts could be subscribed to by alert distributed services, such as sending a slack  or text message.

**Comment by nelsonong** [comment]
Good question. I'm currently working on a threshold detection operator that I've put in a temporary streamsx.alerts toolkit.

It can be attached to the MetricsSource to monitor metrics but it isn't metrics-specific so I wasn't sure if it belonged in streamsx.metrics (for example, it can be attached to the streamsx.health toolkit to monitor heart-rate).

**Comment by ddebrunner** [comment]
I was really thinking about microservices that were based off specific knowledge of metrics, though thinking about it more it may be more along the lines of job state/health.

Doesn't sound like a a threshold detection operator would belong in "metrics", or "alerts", but hard to tell without knowing what it does.

**Comment by markheger** [comment]
new Threshold detection service released with 1.2.0 in the streamsx.monitoring toolkit
