### ISSUE TITLE
Renaming to streamsx.monitoring

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.monitoring#53]
After confirmation of proposal
https://github.com/IBMStreams/administration/issues/120
the repository and the toolkit will be renamed.

_repository name:_
**streamsx.monitoring**

_toolkit name:_
**com.ibm.streamsx.monitoring**

_namespace for MetricsSource_
**com.ibm.streamsx.monitoring.metrics**

**Comment by ddebrunner** [comment]
@markheger Do you know if you have the authorization to rename the repo?

**Comment by markheger** [comment]
@ddebrunner I don't have the authorization to rename the repository.

**Comment by markheger** [comment]
@petenicholls @chanskw Could you please rename the repository to **streamsx.monitoring**.
I prepared the toolkit and samples on **_develop_** branch for the new toolkit name.

**Comment by petenicholls** [comment]
will handle this Monday...everyone on vacation at the moment

**Comment by petenicholls** [comment]
done...renamed the repos.  Please make any updates required to fodlers, documentation, samples etc...
