### ISSUE TITLE
Provide useDefaultConnection option for automatic discovery of JMX connection url

### ISSUE THREAD

**Issue by ilanprager** [IBMStreams/streamsx.monitoring#66]
@markheger has provided a sample that can automatically discover the JMX connection url.
This proposal aims to pull that facility into the operators in the toolkit such that the user could specify a "useDefaultConnection" = true parameter (or even made that the default behavior if a connectionURL isn't specified) and the discovery would happen automatically.

**Comment by markheger** [comment]
If connectionURL isn't specified and applicationConfiguration is not set, then the operator should retrieve the jmxConnect string on its own if domainID matches the own domain or if domainID is not specified.

**Comment by markheger** [comment]
released with 1.3.2
