### ISSUE TITLE
DomainHandler errors on instance created and deleted ChangeNotifications

### ISSUE THREAD

**Issue by ilanprager** [IBMStreams/streamsx.monitoring#69]
Noticed these in the logs - didn't verify whether or not this was only a logging issue or if was preventing these events from being emitted:
16 Aug 2017 13:23:18.081 [5747] ERROR #splapptrc,J[501],P[1280],ChangeNotifications M[DomainHandler.java:com.ibm.streamsx.monitoring.jmx.internal.DomainHandler.handleNotification:130]  - received INSTANCE_DELETED notification: user data is not an instance of String

16 Aug 2017 13:42:46.499 [5747] ERROR #splapptrc,J[501],P[1280],ChangeNotifications M[DomainHandler.java:com.ibm.streamsx.monitoring.jmx.internal.DomainHandler.handleNotification:130]  - received INSTANCE_DELETED notification: user data is not an instance of String

@markheger ^

**Comment by markheger** [comment]
released with 1.3.3
