### ISSUE TITLE
JobStatusSource generates near duplicate events when a PE starts up.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#78]
When a PE starts up I consistently see two events saying it is healthy and running. They only differ in the timestamp.

This may be due to some underlying cause, where the PE has changed but the differences cannot be seen in the notification info. If that's the case then the SPLDOC should document more info about the events and what tuples might be emitted.

```
{notifyType="com.ibm.streams.management.pe.changed",domainId="standard1",instanceId="3a4b0956-ec2c-4cd0-98e7-9da7c70c0fa3",jobId=28,jobName="test2_ec::test_app_log_28",resource="10.143.13.241",peId=29,peHealth="healthy",peStatus="running",eventTimestamp=(1505363270,520000000,0)}
{notifyType="com.ibm.streams.management.pe.changed",domainId="standard1",instanceId="3a4b0956-ec2c-4cd0-98e7-9da7c70c0fa3",jobId=28,jobName="test2_ec::test_app_log_28",resource="10.143.13.241",peId=29,peHealth="healthy",peStatus="running",eventTimestamp=(1505363270,515000000,0)}
```

**Comment by ddebrunner** [comment]
After restarting a PE I saw three identical (except timestamps) with `unhealthy,stopped` pairing.

It's as though a good practice would be to include a `DeDuplicate` operator after the `JobStatusSource`.
Maybe even `JobStatusSource` should be a composite that has the JMX operator followed by a DeDuplicate?

**Comment by markheger** [comment]
Composite JobStatusMonitor containing JobStatusSource->DeDuplicate should be added to the com.ibm.streamsx.monitoring.jobs namespace.
