### ISSUE TITLE
Better default for filterDocument?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#79]
While `JobStatusSource` was fairly easy to get running it seemed strange that I had to copy and paste a filter document from the SPLDOC and then figure out how to use it with the operator.

For the common use with Streaming Analytics service it seems a filter of all jobs and all PEs in my single instance should be easier.

I was thinking the having standard filter docs in `com.ibm.streamsx.monitoring/etc` might be useful, e.g. `jobSourceAll.json`. But I'm not sure if there's an SPL function to pick up the root of another toolkit (there is at the C++/Java operator API).

Then maybe could the default be changed to be include everything, so that `filterDocument` is optional?

**Comment by ddebrunner** [comment]
This may be an issue for all operators that use a filter document, I've only used the `JobStatusSource`.

**Comment by markheger** [comment]
For easier the usage, the filterDocument should become optional for MetricsSource and JobStatusSource. There should be a default value for the "filterDocument". Having a constant string in the operator java code is quite easier than having a json file to be read from the monitoring toolkit.

**Comment by ddebrunner** [comment]
Maybe the default should be all in the current domain **and** instance.

**Comment by markheger** [comment]
yes, current domain and instance as default is optimal.

**Comment by ddebrunner** [comment]
Note that also my first attempt was providing the JSON directly as a `rstring` to the parameter. That didn't work!

Being forced to use a file is a bit of a pain, especially with Bluemix. Allowing a JSON object directly would be useful.
