### ISSUE TITLE
Add notification lost & connection notifications to JMX sources.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.monitoring#82]
The JMX connection indicating notifications may have been lost is useful information for downstream operators. 

Similarly the loss of the connection would be useful.

These are all standard JMX notifications so they should be able to be submitted on the existing schemas, with their existing type and a timestamp, and everything else the default value.

**Comment by markheger** [comment]
@ddebrunner 
I would propose to have these notifications on an optional second output port.
Schema on output port 0 of MetricsSource is different to the schemas of LogSource and JobStatusSource operators, which have notifcationType attribute.

Notifications of type
* jmx.remote.connection.failed
* jmx.remote.connection.notifs.lost
would be emitted as tuple if second output port is present with the right attributes.

**Comment by ddebrunner** [comment]
I guess a second port makes sense, not sure though how one would correlate events across the ports, maybe the event timestamp is sufficient, though since they can come from different machines they may be off by a few ms.
