### ISSUE TITLE
Use multi-threading to retrieve metrics for many MXBean objects in parallel

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.monitoring#9]
The current implementation uses a sequential approach to retrieve the metrics: The operator holds MXBean objects for all monitored objects, OperatorMXBean, OperatorInputPortMXBean, and OperatorOutputPortMXBean. It iterates through all these objects and calls the retrieveMetrics method. The result is processed before the function is called on the next object.

It might be useful to parallelize the function call, for example, processing the metrics of 5, 10, or 20 objects in parallel.

The task is to analyze whether this is a required and useful enhancement, and how it can be solved.

**Comment by markheger** [comment]
not required
