### ISSUE TITLE
MetricSource sample does not work with MetricSomeCustomMetrics.json

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.monitoring#94]
I tried running the sample: com.ibm.streamsx.monitoring.metrics.sample.MetricsSource.
I set MetricsSource_MonitorSomeCustomMetrics.json as the filter document.

The application will not run with the following error

Am I missing something obvious here?

04 Dec 2017 10:10:41.527 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.<init>:-1]  - Unexpected character: [M] while scanning JSON String for JSON type.  Invalid JSON.
04 Dec 2017 10:10:41.527 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - java.io.IOException: Unexpected character: [M] while scanning JSON String for JSON type.  Invalid JSON.
04 Dec 2017 10:10:41.527 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.json.java.JSON.parse(JSON.java:90)
04 Dec 2017 10:10:41.528 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.json.java.JSON.parse(JSON.java:135)
04 Dec 2017 10:10:41.528 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.json.java.JSON.parse(JSON.java:154)
04 Dec 2017 10:10:41.528 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.jmx.internal.filters.Filters.setupFilters(Filters.java:277)
04 Dec 2017 10:10:41.528 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.jmx.AbstractJmxSource.setupFilters(AbstractJmxSource.java:568)
04 Dec 2017 10:10:41.528 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.jmx.AbstractJmxSource.initialize(AbstractJmxSource.java:308)
04 Dec 2017 10:10:41.528 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.metrics.MetricsSource.initialize(MetricsSource.java:336)
04 Dec 2017 10:10:41.529 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
04 Dec 2017 10:10:41.529 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)
04 Dec 2017 10:10:41.530 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_function M[JavaOp.cpp:newBridge:1401]  - CDISR5126E: A Java exception occurred at Operator.initialize() during the JavaOp invocation.
04 Dec 2017 10:10:41.588 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_operator M[PEImpl.cpp:handleOperatorFailure:596]  - CDISR5030E: An exception occurred during the execution of the MetricNotifications operator. The exception is: A Java exception occurred at Operator.initialize() during the JavaOp invocation.
04 Dec 2017 10:10:41.588 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_pe M[PEImpl.cpp:process:1336]  - CDISR5079E: An exception occurred during the processing of the processing element. The error is: A Java exception occurred at Operator.initialize() during the JavaOp invocation..
04 Dec 2017 10:10:41.601 [29091] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_operator M[PEImpl.cpp:process:1367]  - CDISR5053E: Runtime failures occurred in the following operators: MetricNotifications.
04 Dec 2017 10:10:45.715 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.<init>:-1]  - Unexpected character: [M] while scanning JSON String for JSON type.  Invalid JSON.
04 Dec 2017 10:10:45.715 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - java.io.IOException: Unexpected character: [M] while scanning JSON String for JSON type.  Invalid JSON.
04 Dec 2017 10:10:45.715 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.json.java.JSON.parse(JSON.java:90)
04 Dec 2017 10:10:45.716 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.json.java.JSON.parse(JSON.java:135)
04 Dec 2017 10:10:45.716 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.json.java.JSON.parse(JSON.java:154)
04 Dec 2017 10:10:45.716 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.jmx.internal.filters.Filters.setupFilters(Filters.java:277)
04 Dec 2017 10:10:45.716 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.jmx.AbstractJmxSource.setupFilters(AbstractJmxSource.java:568)
04 Dec 2017 10:10:45.716 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.jmx.AbstractJmxSource.initialize(AbstractJmxSource.java:308)
04 Dec 2017 10:10:45.716 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streamsx.monitoring.metrics.MetricsSource.initialize(MetricsSource.java:336)
04 Dec 2017 10:10:45.717 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
04 Dec 2017 10:10:45.717 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)
04 Dec 2017 10:10:45.718 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_function M[JavaOp.cpp:newBridge:1401]  - CDISR5126E: A Java exception occurred at Operator.initialize() during the JavaOp invocation.
04 Dec 2017 10:10:45.782 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_operator M[PEImpl.cpp:handleOperatorFailure:596]  - CDISR5030E: An exception occurred during the execution of the MetricNotifications operator. The exception is: A Java exception occurred at Operator.initialize() during the JavaOp invocation.
04 Dec 2017 10:10:45.783 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_pe M[PEImpl.cpp:process:1336]  - CDISR5079E: An exception occurred during the processing of the processing element. The error is: A Java exception occurred at Operator.initialize() during the JavaOp invocation..
04 Dec 2017 10:10:45.801 [29150] ERROR #splapptrc,J[13],P[13],MetricNotifications,spl_operator M[PEImpl.cpp:process:1367]  - CDISR5053E: Runtime failures occurred in the following operators: MetricNotifications.

**Comment by chanskw** [comment]
I also tried MetricSource_MonitorEverything.json and that did not work either

**Comment by markheger** [comment]
Problem is valid for all operators reading filterDocument as file. This needs to be fixed.
Workaround: Apply JSON string in application configuration

**Comment by chanskw** [comment]
Thanks!  i am reluctant to do that.. due to the issue with constantly checking for app config changes.

**Comment by markheger** [comment]
- in standalone mode it works specifying a file with relative path
- in distributed mode, the file needs to specified with absolute path

**Comment by markheger** [comment]
Operator should support to specify a file relative from application root
