### ISSUE TITLE
How to use the microservices in the streamsx.monitoring toolkit

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.monitoring#95]
I see that in the toolkit, there are a few microservices.  They are small applications that are ready to use... but how would anyone build / launch these services?

Do you expect people to import the toolkit into studio to build the applications?  Is there a build script that would build these applications adn allow them to be run?

In streamsx.health, we have build script that build the services as well as launching the service, without the user having to dive into the details.  Is this something we should try to do here to?

**Comment by markheger** [comment]
Yes, build scripts and README would be a good option to simplify the usage of the microservices

**Comment by markheger** [comment]
Any suggestions or templates are welcome

**Comment by markheger** [comment]
microservices are located outside the toolkit and pre-built in a release
